whyerror/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
whyerror/cli.py,sha256=x97VR5URYrySRxw6NMGgmwbC9zb9NWvJ_2iSI7O1G-o,2073
whyerror-0.0.1.dist-info/LICENSE,sha256=E9EzhV43t6p4nIvGfM8qWh3TW71_DC22Klq6SxQBhlI,1009
whyerror-0.0.1.dist-info/METADATA,sha256=6SE8G3MX7Zxrktn3dA8FqiCg-ghy0NYo8gY_KEe8IaI,192
whyerror-0.0.1.dist-info/WHEEL,sha256=pkctZYzUS4AYVn6dJ-7367OJZivF2e8RA9b_ZBjif18,92
whyerror-0.0.1.dist-info/entry_points.txt,sha256=emqedR3iw5ohTm0XmMU71v1ZGofCr7me1g1BunLGLsk,51
whyerror-0.0.1.dist-info/top_level.txt,sha256=ezq_loM7TfcW-39u3pzZZu_WdTe8QeNR53wRvyqCJwI,9
whyerror-0.0.1.dist-info/RECORD,,
