msgid ""
msgstr ""
"Project-Id-Version: pylav\n"
"POT-Creation-Date: 2024-05-07 00:16+0000\n"
"PO-Revision-Date: 2024-05-21 18:25\n"
"Last-Translator: \n"
"Language-Team: Italian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: redgettext 3.4.2\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: pylav\n"
"X-Crowdin-Project-ID: 535244\n"
"X-Crowdin-Language: it\n"
"X-Crowdin-File: /lib/pylav/extension/bundled_node/locales/messages.pot\n"
"X-Crowdin-File-ID: 3385\n"
"Language: it_IT\n"

#: pylav/extension/bundled_node/manager.py:239
msgid "You are attempting to run the managed Lavalink node on an unsupported machine architecture."
msgstr "Si sta tentando di eseguire il nodo Lavalink gestito su un'architettura di computer non supportata."

#: pylav/extension/bundled_node/manager.py:466
msgid "The output of `{command_name_variable_do_not_translate}` was unexpected\n"
"{command_output_variable_do_not_translate}"
msgstr "L'output di '{command_name_variable_do_not_translate}' è stato inaspettato\n"
"{command_output_variable_do_not_translate}"

#: pylav/extension/bundled_node/manager.py:489
msgid "The port {port_variable_do_not_translate} is already in use. Managed Lavalink startup has been aborted."
msgstr "Il porto {port_variable_do_not_translate} è già in uso. L'avvio gestito di Lavalink è stato interrotto."

#: pylav/extension/bundled_node/manager.py:494
msgid "Lavalink failed to start: {error_variable_do_not_translate}"
msgstr "Impossibile avviare Lavalink: {error_variable_do_not_translate}"

