
class PasswordError(Exception):
    pass

class ProtectedError(Exception):
    pass